language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - ruby-head

before_script:
  - psql -c 'create database mincer;' -U postgres
  - psql -c '\c mincer; CREATE EXTENSION IF NOT EXISTS pgcrypto;' -U postgres

script: bundle exec rspec spec